[build]
  command = "npm run build"
  publish = "dist"
  node_version = "20"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://api.escuelajs.co/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 