[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

[build.environment]
  VITE_API_URL = "https://api.escuelajs.co/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "netlify-plugin-visual-diff"

  [plugins.inputs]
  # Increase threshold for acceptable differences
  failThreshold = 0.10
  # Paths to exclude from visual diffing
  exclude = [
    "**/*.html",
    "**/node_modules/**"
  ]
  # Wait for dynamic content to load
  waitForSelector = "#root"
  waitForTimeout = 5000 